import '@styles/base/global.scss';
import { Inter } from 'next/font/google';
import { ApolloProvider } from '@/client/apollo-provider';
import Navigation from '@/components/Navigation/Navigation';
import Footer from '@/components/Footer/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				{/*<ApolloProvider>*/}
				<Navigation />
				{children}
				<Footer />
				{/*</ApolloProvider>*/}
			</body>
		</html>
	);
}
