import './globals.css';
import { Montserrat, Inter } from 'next/font/google';
import React from 'react';
import { getNavigationAndFooterData } from '@/lib/api';
import dynamic from 'next/dynamic';
const Navigation = dynamic(() => import('@/components/Navigation/Navigation'), { ssr: false });
const Footer = dynamic(() => import('@/components/Footer/Footer'), { ssr: false });

export const metadata = {
	title: 'JDomagala - usługi budowlano-remontowe',
	description: 'Generated by create next app',
};

const inter_init = Inter({
	subsets: ['latin'],
	weight: ['400', '500', '600', '700'],
	variable: '--fontPrimary',
});

const montserrat_init = Montserrat({
	subsets: ['latin'],
	weight: ['500', '600', '700', '800', '900'],
	variable: '--fontSecondary',
});

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const data = await getNavigationAndFooterData();

	if (!data) return null;

	const { navigationData, footerData } = data;

	return (
		<html lang="en" className={`${inter_init.variable} ${montserrat_init.variable}`}>
			<body>
				<Navigation data={navigationData} />
				{children}
				<Footer data={footerData} navigationLinks={navigationData.navigationLinks} />
			</body>
		</html>
	);
}
